let iai = [
  "I was recently added in the Forbes list of the most successful nonprofit executives (Forbes Nonprofit Council).",
  "I was the youngest-ever contender in the largest private boxing event in China.",
  "I started running at 48 and ran my 1st marathon at 51.",
  "I raised two children and went back to school as an adult and was hoping to finish before I reached the age of 40.  I did!",
  "I've written a presidential address about NASCAR.",
  "I'm a buttoned up investment professional, but I used to be a long-haired musician.",
  "I am the only Cambridge Rindge Latin High School Debate Team member to win the First Speaker Award at a debate.",
  "I have an impeccable turkey call... the Brookline turkeys love me.",
  "I was held up at gunpoint as a 19-year-old bank teller.",
  "I'm applying for a PhD program right now and it's one of the most rewarding and terrifying things I've ever done! Imagine if I actually get accepted.",
  "I was Whitey Bulger's neighbor in Santa Monica and didn't realize it was him.",
  "I live with a papier-mâché Boxer named Charlie Hebdo.",
  "At the age of 66 I’ve taken up singing in choruses and am learning songs in 7 languages.",
  "I won a poetry contest while in the Peace Corps in Guatemala in the Q'eqchi language.",
  "The due date on my research paper coincide with the event. You already know what I’m going to choose.",
  "I wrestled an Alligator when I was 12 Years old.",
  "I just spent two years in Barcelona and still can only speak Spanish at beginner levels.",
  "I broke my neck hiking and am all the better for the experience.",
  "I was part of the executive leadership team that started the first human embryonic stem cell research institute in the United States.",
  "I love to travel - I have been to 28 countries so far and hoping to reach 30 countries before I turn 30 years old.",
  "I met the love of my life in 2nd grade, but didn't know it!",
  "I once delivered a baby on a bus.As of 18 days ago, I’m a new dad and I’m ready to make the world a better place for my daughter.",
  "I passed pediatric legislation in MA with no political background or knowledge.",
  "I work with children with brain injuries and help find homes for abandoned dogs and cats.",
  "I’m a competitive surfer at 80, and surfed above the kelp canopy at Sharks Cove.",
  "I have track more than 100 global trends reshaping our world.",
  "Stevie wonder got onstage with me for a jam at my live demo for Roland at the NAMM show 2016.",
  "I aspire to become a Trauma Surgeon for the U.S. Navy.",
  "I have had a bullet in my head since childhood, I’m now a Data Scientist, and I’m learning Ukulele.",
  "I am researching topics that can affect over 10 million lives!",
  "I have never failed to vote in any election where I was authorized to vote.",
  "I have visited 53 major league ballparks in my lifetime.",
  "My friend spoke at TEDxBeaconStreet in 2013 and has 3.5 million views!",
  "I am likely the best disc golfer to attend this event. Handicap +1.",
  "I am a music promoter and have produced events promoting music and peace at the UN!",
  "I just got married for first time at 64!",
  "I served the Peace Corps in Mongolia from 2008-2012 when I was 65.",
  "I've worked as a consultant in over 60 countries around the world.",
  "My family has watched countless Ted Talks through the website since I was younger, and I am so excited to finally see some live!",
  "I've saw shadow bands on Nauset Beach during the solar eclipse of 1970. ",
  "I live - literally - on the water of San Francisco bay.",
  "Completed a project for GM to train 1000s of employees.",
  "In my 20s, I was a radio disc jockey and had a motorcycle.",
  "I enjoy the intersection of team sports and business practices.",
  "I was a therapist in post-communist Prague for 20 years.",
  "I am on a JF Kennedy scholarship in Harvard currently.",
  "I consider myself an ecological person, so I do things like reuse used (but not too much) paper napkins. I don’t like any kind of waste.",
  "At the age of 45 I decided to change my life and here I am, close to the opening of my first healthy fast food restaurant.",
  "I honeymooned under a mosquito net in a jungle camp hut in the Amazon.",
  "I Enrolled in  Culinary School at the age of 54!",
  "In college, I was hitchhiking on Martha's Vineyard, and Billy Martin picked me up.",
  "I was on an Easy Bake Oven box.",
  "I am a researcher working on cancer biology. I have two patents about drug candidates.",
  "I lived and worked in Nigeria and left after a military coup.",
  "I have had a smoke of one of Fiedel Castros very personal cigars!  Very nice!",
  "I have been working at the same institution for 50 years.",
  "I play alternate shot golf with Special Olympics.",
  "Every night I have to sleep in a different pijama.",
  "I got my '23&me' analysis 5 years ago. Currently I am excited to reach out and visit some of my close cousins around the world.",
  "I am a huge fun of the worst football team ever.",
  "There's a fissure in a cave in Florida named after me.",
  "I bicycle more than 1000 miles per month.",
  "I am currently using an 'artificial pancreas' to manage my diabetes.",
  "I'm missing a tooth. My orthodontist just moved all my teeth on that side over a bit to make up for it.",
  "I'm a rapper and PhD candidate at MIT in machine learning who created the first rap with lyrics generated by a computer.",
  "I volunteered in Zambia to build IT infrastructure for a local elementary school.",
  "I took a sabbatical year to travel around the world and visit 20+ countries.",
  "I once carried the Olympic Torch!",
  "I have hiked the Grand Canyon Rim to Rim.",
  "I have two different first names on my passport separated by an aka.",
  "I've eaten fire before.",
  "I don't believe in the phrase there's no time for that.",
  "I am a mom to a child with AUTISM, AUdiologist and AUthor of Au-mazing Gift A Journey to Autism Acceptance.That makes me triple AU-MAZING!",
  "I solve protein 3D atomic structures!",
  "During the course of a being the best man at a Hindu wedding in India, I was unknowingly converted to Hinduism.",
  "I can do a single arm pushup and frogstand.",
  "I once briefly trained in Olympic luge in in Lake Placid when I was 13.",
  "I have climbed Mt. Kilimanjaro.",
  "I am starting an interesting company that aims to improve the mental health of mankind through a combination of AI and psychology",
  "I met my wife on the radio.",
  "I am working on  a research project with my cohort to improve the neighborhoods of Boston.",
  "I once worked in a steel mill in Homestead, PA.",
  "I crossed Nigeria in a Mercedes taxi straddling a hole in the floor.",
  "I am currently producing and directing my first documentary about the homeless.",
  "I'm a farm boy who transplanted to Boston 35 years ago and wish I could have led dual lives here and on the farm.",
  "I'm reading biographies of the presidents in order.",
  "I'm an affordable housing, economic development  and neighborhood revitalization revitalization  professional.",
  "I am a twin and my mom is a twin!",
  "My mother once went on a double date with Robert Kennedy.",
  "I once ate so many papayas over the course of 3 months that I developed carotenemia and turned noticeably orange.",
  "I bicycled to this event!",
  "I visited my future spouse in Gaza by going through a tunnel from the Egypt side and had a great time there.",
  "I interned for Senator Kennedy in the Boston Office and helped at the Kennedy Library dedication.",
  "I recently found a very interesting historical document during my research. Nothing like this has ever happened to me before!",
  "I am one of 9 children and have a sister with the same name.",
  "In summer 2016 I walked 150 km from Bologna to Florence through the mountains",
  "I've climbed an active volcano in Guatemala",
  "I'm the lady who went to JAIL for 60 Days Undercover though a no acting all reality based TV Show on A&E called 60 Days In.",
  "I've been tackled by the Secret Service.",
  "I almost drowned in the Ganges (largest river of India) 2 times.",
  "I organized the first TEDxYouth event in Dubai!",
  "I just became a farmer.",
  "I went to President Obama's first inauguration in 2009!",
  "My great (x4) grandpa built a windmill in the Netherlands in 1852. It's still functional and is now a museum.",
  "I am a 7th degree Black belt in Judo.",
  "I flew in a tour helicopter in Hawaii, all the while terrified and hanging on to my 83 year old mother!",
  "I had White House security clearance.",
  "I commute on a boat.",
  "I once did a homestay with a potato farmer from Peru who is part of the indigenous community Nacion Q'eros--the last descendants of the Incas.",
  "I was smuggled over the Berlin Wall in 1987 to get to the East side.",
  "I was born at 2 lbs and 12 ounces in 1986. Thank you Brigham's and Women's for saving my life!",
  "I’m 42 and thinking about applying to med school.",
  "I dated a circus clown.",
  "I am an extra in a John Travolta film.",
  "I'm a liver transplant survivor.",
  "I have traveled to all 7 continents before the age of 30",
  "I have the odd habit of laughing at the wrong times and wrong places.",
  "I have 150,000 twitter followers!",
  "I can file a U.S. patent application or a PCT patent application for anyone anywhere!",
  "I climbed the Great Wall of China!",
  "I have synesthesia- all of my letters and numbers are associated with a color.",
  "I have traveled around the world on $1,000.00.",
  "I was born purple.",
  "I am a former Peace Corps Volunteer.",
  "I'm proud of my  'awthentic' Boston accent.",
  "I've been in a show on Broadway!",
  "In my earlier days I was a supernumerary for several season with the Washington National Opera.",
  "My great-uncle was JFK's best friend in the senate.",
  "I listen. Sometimes I hear.",
  "I work with honey bees.",
  "I am willing to take on any challenge even though I have no clue how to do it, such as making a parachute after I jump out of the plane.",
  "I have a small farm in Vt making hard cider!",
  "I have a tattoo of a unicorn. It’s symbolism for believing in something even when nobody else does - and that something being magical.",
  "I enjoy organizing the high-tech forums on AI, IoT, Cloud, Deep Learning, Big Data, etc. to benefit the IT professionals.",
  "I've been a beekeeper for two years and I've found that honey is the best free gift during the holidays!",
  "I broke into a Concentration Camp in Germany!",
  "TEDx is part of my tools to grow as a human being.",
  "A direct ancestor of mine signed of the Declaration of Independence.",
  "I ran the Boston Marathon.",
  "I am a soccer goalie.",
  "I row boats!",
  "I'm crushing my coworkers at Fantasy Football this year.",
  "I lived in a dung hut in Kenya.",
  "I like to draw with charcoal.",
  "I come from a country that doesn't have trains!",
  "My first sewing project was plaid overalls when I was 9 and the pattern matched!",
  "I played ice hockey in high school",
  "I am an artist",
  "This is my very first time watching TED talk in person - and I’ll get to watch my husband!",
  "I've built robots at the European Space Agency!",
  "I've worked in Special Education for 42 years.",
  "I have worked with governments in many different countries.",
  "I qualified for the Ironman 70.3 World Championships being held next year in South Africa.",
  "I am in a graduate program at Case Western Reserve.",
  "I am always looking to better myself.",
  "I recently moved to Boston and look forward to getting to know more of the city!",
  "I programmed the children's game Othello with an AI language years ago and was shocked when it beat me!",
  "I hope to someday hold a TEDx talk in Haiti.",
  "I play with Lego as my daily job!",
  "I'm a member of the AMC New England 4,000 footer club.",
  "I've lived in seven different countries by the age of 30.",
  "I've been on a safari in South Africa.",
  "I have lived in three continents.",
  "I have no religious ties to any one entity and I'm ok with that.",
  "I am an Irish Jew",
  "I am someone who can make friends with almost anyone.",
  "I have carried coals to Newcastle.",
  "I used to be a gymnast!",
  "I farmed tobacco.",
  "I love skiing!",
  "I'm a plant collector.",
  "I have an identical twin.",
  "I worked in a DNA lab before going into Social Work.",
  "I can read and write Hebrew but have no idea what I'm saying.",
  "This will be my 1st Tedx session!",
  "I sang in every talent show from kindergarten through 6th grade",
  "I still have memories of my crib.",
  "I was once arrested in Beijing.",
  "I served the Queen at a function in NZ.",
  "I'm a yogi-psychiatrist-changemaker and almost drowned as a baby.",
  "I have worked at Japanese culture sector.",
  "I'm running a marathon the day after this event.",
  "I'm a big fan of TEDX Beacon Street!",
  "I am a designer working in nanotechnology!",
  "I am a poetry buff.",
  "I am a photographer.",
  "I am 75 and a texting junkie.",
  "I have flown in Zero-G.",
  "I traveled the world for two years.",
  "I'm a proud TEDx organizer!",
  "This is my first TEDxBeaconStreet talk.",
  "I am a retired Marriage & Family therapist.",
  "I am curious.",
  "This is my First TEDxBeaconStreet event.",
  "I've watched 'Ghostbusters' at least 20 times.",
  "I like parsnips.",
  "If I could only eat one dessert for the rest of my life, it would be brownies.",
  "I went to school in Boston.",
  "I have a wonderful assistant named Dan who can't think of anything to put here.",
  "I made a world famous joke app.",
  "All of my post college positions have been with small businesses.",
  "I once swallowed a quarter.",
  "I could be Superman and you wouldn't know.",
  "I have had three near death experiences!",
  "I speak a few different languages.",
  "I watch TEDx Videos to help me get out of bed sometimes.",
  "I am responsible and joyful!",
  "In the last few years, I've served on a two juries, including a murder trial.",
  "I won a kazoo-playing contest when I was a kid.",
  "I am the Chief Medical Officer at Moderna Therapeutics.",
  "This is my first TED event!",
  "You Can Take Me out of NYC but you Can't Take NYC out of Me",
  "My closest friend is the mother of one of the speakers!",
  "I am a level 36 Pokemon Go Trainer!",
  "I am 34.5 and have never mowed the grass.",
  "I just ran my 2nd marathon this past weekend!",
  "I am a painter.",
  "I have conversations with the moon..",
  "I think TED talks are awesome!",
  "I am a girl scout gold award recipient.",
  "I am in Boston to tour MIT.",
  "I host a Top Podcast Show",
  "I am a highschool student in Boston this weekend to tour MIT.",
  "I am an advocate for autistic people!",
  "I am a public servant of Colombian heritage, born in California, living in Boston",
  "I did my first air travel at age 22.",
  "I almost won a car in a clean energy idea competition.",
  "My favorite indulgence is going to a steak house!",
  "I have cycled miles all around the world!",
  "I love ice cream!",
  "I love bread pudding!",
  "I love to travel.",
  "I just got my driver's license.",
  "I am a builder.",
  "I am a photographer.",
  "I am a cancer survivor!",
  "I have been to Israel!",
  "I can juggle!",
  "I play the flute.",
  "I am a teacher.",
  "I love mountain biking and my favorite place to go biking was Hong Kong!",
  "I live the mix of art and science.",
  "I believe that leadership is ageless!",
  "This is my first Tedx!",
  "I’m Pregnant!",
  "One time I bicycled from Maine to NYC.",
  "I have lived in Florida, Colorado, Virginia, Massachusetts, and California!",
  "I've only been in Boston for a year and I love that I'm still exploring the city and learning new things from people I meet along the way.",
  "I can walk on my hands!",
  "I love to cook!",
  "I have a Weimaraner puppy named Aristotle.",
  "I grow my hair long in order to donate it!",
  "I am one of two sets of twins!",
  "I was at the main TED conference in Kobe, Japan in the 90s",
  "these are the questions that stress me out",
  "I love sea kayaking!",
  "I love to sing!",
  "I volunteer at the Brookline Teen Center!",
  "I lived in Spain and speak fluent Spanish!",
  "I am an incredible pianist!",
  "I got lost hiking in Maine last weekend",
  "Sometimes I just know things :)",
  "I have been in two major movies.",
  "I have a pet snake",
  "The JFK library is the first thing I see when I wake up and the last thing I see before I go to bed.",
  "I can do headstands.",
  "I am both an early-riser and a night-owl",
  "I'm attending my first TEDx conference!",
  "I like to sail.",
  "I like to cook.",
  "My mom is my best friend.",
  "I love researching at JFK Presidential Library.",
  "I lived in Hawai'i for 3.5 years and love poi.",
  "I love to snow ski.",
  "I co authored a book with my son about autism.",
  "I am the mother of an adult son on the autism spectrum.",
  "I grow citrus trees in the boston suburbs",
  "I was on Zoom at age 9.",
  "I am a friend of Speaker Tyler Lagasse.",
  "I smile a lot.",
  "I have planted 3,000 daffodils on a hillside.",
  "I attended an all Black college.",
  "I am a plumbing teacher.",
  "I was raised in an island, and I don’t know how to swim.",
  "I have been a speaker sparkplug!",
  "I travel a lot!",
  "I wrote and published a book about urology for the public.",
  "I professionally study stories.",
  "I'm obsessed with the show Project Runway.",
  "I am training for an ironman!",
  "I never wear pants.",
  "I'm a Marathoner.",
  "I have an uncanny ability to remember people by their faces and occasionally by their names!",
  "I like apples but hate apple juice.",
  "I am the only part time fire protection engineer that I know about-mostly to allow me to spend time with my twin daughters.",
  "I love JFK and have read 10+ books on the Kennedy.",
  "I appreciate being stereotyped because I fit into them so well that it saves a lot of explanation.",
  "I rode 3500 miles on the back of a motorcycle",
  "I love to sew.",
  "I enjoy sports!",
  "When I listen to music, I hear the harmonies, not the melodies.  I have to really focus to pick out the main melody.",
  "I'm highly motivated to run for public office sometime in the near future.",
  "I love studying US History.",
  "I really enjoy bouldering and other types of rock climbing.",
  "I am a student at BC.",
  "I am allergic to the sun!",
  "I am a farmer.",
  "I am a lifelong learner",
  "I have 7 dogs.",
  "I’m a professional pastry cooker.",
  "I am a fan of special olympics.",
  "I am pursuing my physics PhD while doing research in AI.",
  "I was a competitive figure skater for 8 years.",
  "This will be my first TEDx event!",
  "I like to wear Batman socks when I need good luck.",
  "I like Teslas!",
  "I love plants and foliage!",
  "I plan to visit every country within the next 20 years.",
  "I like ice cream.",
  "I love rock climbing.",
  "I am a student.",
  "I was a former TEDx speaker.",
  "I'm from Germany.",
  "I learned how to ride a bike when I was 18.",
  "I am a yoga teacher.",
  "I like cats.",
  "I believe that they only way to graduate happily is to work hard without expectations.",
  "I believe that young entrepreneurs are the key to transforming the biotech innovation industry!",
  "I have lived in four continents.",
  "This is my first TEDx event.",
  "I sing operatic arias.",
  "I am a proud child of immigrants.",
  "I was born on the 4th of July!",
  "I've been lost on top of a mountain in Norway!",
  "I recently figured out that I have ADHD!",
  "I love my Baby Bella!",
  "I have ran a marathon.",
  "It’s impossible for me to hear music and not dance!",
  "As a former high school theatre teacher, The Miracle Worker was the first drama I directed.",
  "I have been to every continent.",
  "I'm a writer.",
  "I learn about the character of a person by playing golf or poker with them.",
  "I’m Bald!",
  "I’m slightly allergic to penicillin.",
  "I once fell asleep for 21 hours straight!",
  "I like creating scavenger hunts.",
  "Tyler is my brother.",
  "Tyler is my brother in law.",
  "I spend my time playing with cool, new microbes!",
  "I LOVE coffee.  I can drink it all day long!",
  "This will be my first Ted Talk, hence I am very anxious.",
  "I coach leaders in the entertainment industry.",
  "I’m launching a new company to help people with disabilities access the world around them.",
  "I'm Captain of my Hockey Team",
  "I danced with Boston Ballet as a teenager.",
  "I created the portable girlfriends club.",
  "I enjoy working on cars.",
  "I am a Military Veteran.",
  "I love scallion pancakes!",
  "I love spicy food!",
  "I watch TED talks during lunch everyday!",
  "I’m interested in the future of tech.",
  "I worked on a NASA satellite mission.",
  "I have never been to the JFK",
  "I am allergic to all raw fruits and veggies.",
  "I can paint backwards!",
  "I lived in France for 14 years.",
  "I found out I was adopted when I was 27.",
  "This is my first time attending a Ted Talk and I'm here to support one of the speakers of whom I am so proud!",
  "I don't do sweets and desserts in front of people but eat tons of them.",
  "I just came out to my family.",
  "I love TedTalks.",
  "I study computer science but dream of working in poverty alleviation.",
  "My work was featured in the Huffington Post.",
  "I am an Engineer.",
  "I love breakfast in bed listening to Justin Bieber.",
  "This is my first time at a TEDx.",
  "A college math major, a trained Kodaly music teacher, a closet techie, and a professional storyteller: all these make me who I am.",
  "I am a photographer.",
  "I speak 4 languages, 5 if I'm drunk.",
  "I am training to ski in the Canadian ski marathon",
  "I burnt my toes on a campfire and I had no idea I did it.",
  "I am a novelist about to publish my third novel.",
  "I fell into the Charles river during my first sailing lesson.",
  "I can look at google maps for hours at a stretch with a very high enthusiasm!",
  "I once earned a red card playing high school lacrosse.",
  "I volunteer helping kids in Boston schools learn to read.",
  "I had a teenage obsession with rainbows.",
  "I can sew sails.",
  "This is my first live TED Talk!",
  "I am a cellist.",
  "I am a neuroscientist.",
  "Ballroom dancing is a hobby of mine",
  "I inspire the next gen of creative thinkers and innovators.",
  "At 16 years old, I am a certified yoga teacher.",
  "My first job was working in a Deli.",
  "I went skydiving from a rickety plane with an inebriated tandem instructor in Hawaii.",
  "I love road trips & vegan soft serve!",
  "I'm from Sweden and mother of four children.",
  "I am always looking for new ways to improve myself and community.",
  "No one ever guesses my ethnicity,or upbringing/background accurately, ever.",
  "I am a plumbing teacher.",
  "I had skull decompression surgery in 2013.",
  "I moved recently from AZ.",
  "I love pretzels! Especially the ones covered with chocolate!",
  "I love pretzels! Especially the ones covered with chocolate!",
  "I love shooting videos it’s a passion.",
  "I'm bad at math!",
  "I am passionate about gender equity in entrepreneurship.",
  "I’m an avid Ted Talk enthusiast and I am excited for my first live event!",
  "I blog!",
  "I am an urban beekeeper.",
  "I once accidentally bear-sprayed myself",
  "I had a friend Speak and she seemed so nervous but convinced me that we can all do it.",
  "I am sometimes lonely.",
  "I love to write a book of plays for children.",
  "I love to travel and be outdoors.",
  "I have run a half marathon.",
  "I wear unmatched socks.",
  "I love making friends.",
  "I like to workout.",
  "Problem solver",
  "I don't believe in the moon.",
  "I cannot whistle or snap my fingers, despite my best efforts.",
  "I love Ted Talks!",
  "I like The Who.",
  "My two kids have two different last names - one has mine, one has my spouse’s.",
  "Technologist of Amish ancestors.",
  "One of my greatest accomplishments was founding a non-profit community theatre group.",
  "I was on the front page of my local newspaper when I wrote to President Clinton in 1996.",
  "I lived in China for 4 years.",
  "In my retirement I learned that I can paint but that I still can't learn languages.",
  "I recently departed fats domino on the loss of his home in the 9th ward  'Whatever goes up gotta come down some kinda way.'",
  "I'm Irish citizen.",
  "Spinal tap is my favorite movie.",
  "I am worldly.",
  "I find that most people can not tell the difference between science and technology.",
  "I am an aspiring farmer.",
  "I'm fun.",
  "I camped out on Martha's Vineyard for two summers.",
  "I love history and was lucky enough to meet the Prince and Princess of Wales when they came to the US.",
  "I was invited to speak at a major conference about a very sensitive subject - GS",
  "I am interested because of previous Ted talks.",
  "I am a proud manager of the Aluminum Monsters.",
  "I've loved helping former students to expand their worldviews.",
  "I am a ballet dancer who’s studying Government at Harvard University!",
  "I swim in the ocean on New Year’s Day to start my year off right.",
  "My ambition is to deliver a TED talk one day!",
  "I am a curious life long student of science and knowledge is my lifeblood.",
  "I grew up in Oregon.",
  "I graduated 1st in my class from the PSU College of Engineering in 1980.",
  "I grew up on an Urban Farm in Boston.",
  "I'm am ardently liberal USAF veteran.",
  "I have read the New York Times every day since I was 14.",
  "My dad was a WWII vet.",
  "I have not been to a Ted community talks yet.",
  "I like to travel and learn new languages.",
  "I have 5 middle names.",
  "I can make a very good bird call.",
  "I judge bookstores on whether or not they separate sci-fi and fantasy.",
  "I love macaroni and cheese.",
  "I am a Sundance Film Festival participant.",
  "I am a Cape Codder.",
  "I have never owned a car.",
  "I am a returned Peace Corps Volunteer - Yemen.",
  "I was on Jeopardy.",
  "I have visited 9 countries in 2017.I think the Chinese totalitarian regime may collapse at any moment.",
  "I am passionate about music photography.",
  "I just ran my first NYC Marathon - my second marathon ever!",
  "I love music.",
  "I love to garden.",
  "I personally know some past TEDx speakers.",
  "I have study JFK letters and speeches religiously.",
  "I just went to Tanzania.",
  "I am a blossoming artist.",
  "I have spent two years teaching university in Tanzania.",
  "I can speak 3.5 languages.",
  "I am Sea trekking certified.",
  "I speak Gaelic fluently.",
  "This is my first TED talk.",
  "I plan to open a dog rehabilitation clinic.",
  "Studying philosophy & history & interested in this TEDX event!",
  "I'm super excited to attend a TED talk!",
  "I am an accidental event planner.",
  "I am a venture capitalist.",
  "I love baseball.",
  "I had a crayfish as a pet.",
  "Staff member of Congresswoman Katherine Clark.",
  "I love Star Wars!",
  "I saw JFK in person in Boston.",
  "I'm a Delawarian.",
  "I like to fly in my mind.",
  "I am a lover of all Politics.",
  "Interested in Public Speaking.",
  "I used to be  graphic designer.",
  "JFK's words have shaped my life positively!",
  "I love learning and experiencing new things.",
  "I have lived in 3 of the commonwealths in the USA.",
  "I love Hiking.",
  "I just returned from a river cruise in central Europe- learned a lot!",
  "I own a multi-award winning business and am launching another.",
  "I am an ex peace corps volunteer.",
  "I would like to be on the stage some day!",
  "I am a senior.",
  "I've watch TED talks on TV.",
  "Born right down the street from JFK.",
  "I like to play the accordion.",
  "I attended a TEDX in Valencia Spain",
  "I enjoy moving house every year.",
  "I come from Sichuan - they have the best food in the whole world.",
  "I am always inspired by the Tedx Speakers.",
  "I am a huge World of Warcraft fan. Go Alliance!",
  "I am interested in the history of the Kennedy clan in Brookline.",
  "Retired tv news cameraman.  Fluent in Russian.",
  "Masters in Environmental Sciences.",
  "I am a retired tv news cameraman and speak fluent Russian.",
  "I like space travel.",
  "I am a senior tech advocate.",
  "I am excited about attending TEDxBeaconStreet for the first time!",
  "I aspire to become a public speaker.",
  "In my spare time I like to photoshop my friend's faces onto Annie Leibovitz photos",
  "I once appeared on the cover of Sports Illustrated.",
  "I am a photographer, an artist, and a writer.",
  "I am a theatre actor.",
  "My friends are in 150 countries across the world. These are people I know personally not on Facebook.",
  "I have discovered the OLLI program at UMB which is a wonderful community of lifelong learners",
  "I am a student this year at MIT.",
  "Author of Tax Your Imagination! The road to a debt-free and inflation-free economy.",
  "I am a joke fan.",
  "I am a motivational speaker.",
  "The older I get, the more I appreciate this wonderful city and the opportunities for continuing education like this, available to all.",
  "I am Grenadian.",
  "I am single and living in Wellesley!",
  "I invented the spiral light bulb!",
  "While working as a Travel Counselor, then as a Financial Analyst, I also recorded all the on-hold announcements for a tour operator",
  "I tried the magic mushroom in Amsterdam last year!",
  "Fiscally conservative, Socially liberal Active Catholic Democrat.",
  "Company sponsored student from Japan.",
  "I like cycling.",
  "I inherited an apple orchard.",
  "I have been a speaker at a past TEDYouth event!",
  "I've run for political office.",
  "I love to dance Salsa. I crochet.",
  "I am a pilot.",
  "I grew up in NYC while JFK was President; I've been a lifelong supporter.",
  "I am a recovering engineer.",
  "I got to a college of less than 400 people.",
  "I am here visiting my daughter from Scotland.",
  "I am Haitian American.",
  "I listen to Ted Talks while I workout.",
  "I love racing yachts.",
  "I am a big history buff.",
  "I founded and direct a peer-support network and advocacy organization for trauma survivors.",
  "I enjoy rowing.",
  "I attended a TEDX in Valencia Spain.",
  "I’ve passionate about languages and have been teaching for 50 years!",
  "I can remember up to 7 digits of π!",
  "I am a Japanese surgeon.",
  "I am half Tanzanian.",
  "I am a former speaker!",
  "I think math is fun.",
  "I love my work.",
  "I create art by manipulating light to create new mediums of expression.",
  "I am a very fast speedreader.",
  "Turns out we all have the same fears and share the values no matter what our background.",
  "I like to eat green apples with salt!",
  "I have been inspired by TED Talks in the past and can't wait for this event!",
  "This is the first time attending TEDxBeaconStreet.",
  "I'm a great hula hooper.",
  "I am embracing the values and culture both of our country and Europe.",
  "I am originally from Texas.",
  "I am a filmmaker.",
  "I’m from Syria.",
  "I slept overnight on the top of the Acropolis.",
  "I have 3 kids.",
  "I'd secretly love to live of the grid!",
  "I am a former Peace  Corps volunteer.",
  "I can't eat square sandwiches.",
  "I am going back to school after turning 40.",
  "I support everyone's right to take a knee.",
  "I am Hungarian.",
  "I am a Peace Corps Mongolia returned volunteer.",
  "I am an Engineer.",
  "I’m currently attending college and will graduate in the Spring.",
  "My EQ is lower.",
  "I love the forum discussions at JFK Library.",
  "I am an assisting minister with Funeral Ministry at my church.",
  "This is my first TEDx event.",
  "I am interesting in marketing study.",
  "I've enjoyed skiing and horseback riding in the Andes Mts.",
  "I am a fitness/wellness motivator.",
  "I have funky feet.",
  "I love looking at cell morphology under the microscope.",
  "I love basketball.",
  "I love reading poetry.",
  "I hope to make documentaries on health care after graduating medical school.",
  "I like disco!",
  "I have dual citizenship from the United States and Canada.",
  "I earned silver medals in the Atlantic Regional USAPB Women’s doubles and mixed doubles Pickleball tournament held in October in Hartford.",
  "This is my first time attending a TEDx event!",
  "I love huskies.",
  "I lIve off of coffee.",
  "I am currently living in a basement apartment.",
  "Just ran my first 5k and won my class!!",
  "I practiced and performed Chinese folk dance for 12 years of my life.",
  "I'm from Kathmandu, Nepal!",
  "I went skydiving!",
  "I like to listen people rather than speak. And surprisingly most people speak to me about all their life including personal life.",
  "Grew up going to Kennedy Park, Wexford",
  "I have cage dived.",
  "I can't snap my fingers.",
  "Kit is the best!",
  "I have ridden my bike 100 miles round Lake Tahoe",
  "I'm a social curious and I always need to build constructive relationships!",
  "I am very interested in psychology but I know nothing about it.",
  "This year I began classes on TaiChi.",
  "I am an avid gardener.",
  "I am a bridge Inspector.",
  "I have a dog named Patches.",
  "I coach all my sons sports.",
  "My favorite food is dill pickles.",
  "The first time I went skiing, they brought me down on a sled.",
  "I hate to drive.",
  "I can hit a field hockey ball a mile.",
  "Talk is not cheap. TEDxBeaconStreetTalk is free.",
  "Gronk",
  "I am a practicing Nicheren Buddhist.",
  "I oil paint.",
  "I home two passports and some of my children hold three.",
  "Former Director of Boston Redevelopment Authority.",
  "I am about to become a US Citizen.",
  "I consider myself very ordinary.",
  "Can't wait to see Tyler share his experience.",
  "I am a Canadian and Irish citizen.",
  "I believe privacy is underrated.",
  "I don't have an appendix.",
  "Mayflower Descendent, lawyer, teacher, small business owner.",
  "I think women should be 50% of every legislative body in the world.",
  "I am defined in a dictionary.",
  "My grandfather William J. O'Callaghan was born in Boston and my sister taped her HBO comedy special at the Wilbur Theater in Boston.",
  "I have a penchant for day old, cold, Big Macs. Fortunately it's a once in a VERY blue moon kind of craving.",
  "I can hit a wiffle ball a mile.",
  "I am a hiker.",
  "Innovation turns me on!",
  "I am a Shriner Clown.",
  "I have a fear of public speaking.",
  "I raise chickens.",
  "I am a dancing machine.",
  "I am sarcastic.",
  "I ate a snail when I was 3 years old.",
  "I love Tedtalks!",
  "My oldest memories are social justice related.",
  "I can smile and frown simultaneously.",
  "I want to help patients in the medical field by creating medical devices for them.",
  "I once travelled to Spain.",
  "I am a Russian bass and can reach a low A.",
  "I Love to scuba dive.",
  "I mentor young men through Year Up in Boston.",
  "I was born in Boston but can't name a single Red Sox player.",
  "I like TED Talks.",
  "Play the banjo!",
  "Road my bicycle across the USA.",
  "I started picking up guitar at 54 years old but discovered I was even better at painting!",
  "I am obsessed with pizza.",
  "I'm a mentor for young women through Year UP in Boston.",
  "I've risen a bicycle cross country",
  "I was on the Better World by Design Committee.",
  "I love to make connections between the arts and other fields",
  "I have a keen interest in Astronomy.",
  "I love helping others thrive.",
  "JKF is my favorite president.",
  "My granddaughter loves these things and I’m here to support her.",
  "I believe in accessibility and equal rights for all people.",
  "I love TEDx Talks!",
  "I am outgoing, smart, and a patriot!",
  "I tell stories through photography and graphics.",
  "I'd like to go on Jeopardy!",
  "I became a documentary filmmaker at age 60.",
  "I am an independent thinker.",
  "Enthusiastic World Traveller",
  "I used to be on BBC Radio Sussex medical call-in show many years ago. I like to help make science and medicine accessible to all",
  "This is my first Tedx.",
  "I recently retired and moved to MA from IL",
  "I’d like to be a foster mom.",
  "I have been a foster mother twice.",
  "I am glad to be here.",
  "I have been Waterfire Volunteer Boat Captain and other roles for the last 10 years and continue to work for this great Non-profit",
  "I loved driving around Iowa.",
  "I'm half Macedonian.",
  "I am excited to attend my first TEDx event - I love listening to the TED Radio Hour on NPR!",
  "I have been an Immigration Attorney since 1994.",
  "I was born in Uruguay.",
  "I used to work in radio and suspect many others have also",
  "I'm a social worker who likes IT.",
  "I built guitars using cigar boxes fished out of dumpsters and parts from Home Depot.",
  "I just came back from 2 weeks in Africa.",
  "I recently returned from Africa.",
  "I love pizza and puppies :)",
  "I hate pizza but I love my girlfriend and want her to marry me.",
  "I actually ran and finished my first marathon at age 46. it was the Boston Marathon, and it took me well over 6 hours!",
  "I drink milk and whisky.",
  "Visiting Antarctica would complete the set.",
  "I graduated high school at 16 years of age.",
  "I listen to Ted talks on NPR and online, but have never attended one!",
  "I'm not very good at it but I like to play pool.",
  "I create mosaics.",
  "I have been diagnosed with Cerebral Palsy as a baby. I'm an artist and run a non profit.",
  "I believe there is beauty in imperfection.",
  "My daughter and I run a non profit for helping patients.",
  "I'm making robotic art.",
  "I pilot satellites.",
  "I am here on a 1 year adventure trip to the U.S.A.",
  "I like lectures.",
  "Was a sushi roller in college.",
  "I am a twin.",
  "I was a lifeguard in college.",
  "I’ve stared down a rhinoceros face to face in the wild.",
  "I’m a child psychiatrist",
  "I worked my way through college giving tours about the Amish.",
  "I’ve completed the century bike ride at Mt Greylock.",
  "I love to dance.",
  "I grew up in the midst of vineyards in southern Switzerland.",
  "I am a service volunteer.",
  "I grow corals in my house.",
  "I walk at least 5 miles on most days.",
  "I like colours I like reading minds.",
  "I love hiking more than any person I know..",
  "I have two different sized thumbs.",
  "Born in London, lived in Hong Kong and now attend Boston Conservatory.",
  "If someone said, you can't own a tv, a hair brush or a car... I'd survive. if someone said, you can't ever travel I would perish.",
  "I love to rock climb.",
  "I ferment my own pickles.",
  "I've played violin in 9 different countries and plan to play in more.",
  "I produced films to serve the social sector.",
  "I'm addicted to Clash of Clans.",
  "I was the city archery champion, at age 12.",
  "I find Elon Musk more interesting than the Kardashians.",
  "I have spent time with two Pulitzer Prize winning journalists.",
  "I organize and curate Canada's largest 1 day orientation program (nearly 10 000 incoming students and supporters).",
  "I have traveled to over 40 countries and lived abroad my entire life.",
  "I'm hoping to write a piece on the Service block to share with the Service-Learning and Community Engagement community at Northeastern.",
  "I want to reinvent myself when I turn 60 years old (in 3 months).",
  "I have never been to a Ted Talk!",
  "I'm a film critic on the side.",
  "I've never been to a Ted Talk.",
  "I prefer barbeque fish.",
  "Love rocking on Pawleys Island.",
  "Worked with Refugees for 6 months this year! Trying to create a new model for refugees.",
  "My daughter is pregnant with our first grandchild.",
  "I spent 7 days in the wood for music's sake!",
  "I just moved from AZ to MA.",
  "I have attended TEDx around the world.",
  "I have 3 daughters.",
  "I love Seinfeld, using comedy to relieve tragedy, and all animals.",
  "I love TEDx.",
  "A broken leg began a career in music.",
  "I ate too much halloween chocolate and it kept me up all night.",
  "I enjoy sailing my sailboat and riding my motorcycle.",
  "My father is Deafblind and I now work with Deafblind individuals and assist them in their learning and understanding of the world around them.",
  "I light birthday candles in binary.",
  "I speak 5 languages.",
  "As a former teacher, I've been trained to address audiences, and would now like to launch a career of public speaking.",
  "I eat the same thing for breakfast everyday.",
  "I studied abroad in Sydney, Australia to start off 2017!",
  "I once drove from California to Connecticut!",
  "I have travelled in almost 30 countries, have lived in more than 3 countries, and my dream  is to travel the world!",
  "I am an ice cream maker for an 84 year old ice cream parlor.",
  "I'm afraid of birds.",
  "I can solve a Rubix cube in under one minute.",
  "I've broken two world records.",
  "I've always wanted to attend a TEDx event.",
  "I speak 4 languages!",
  "Flamenco guitarist.",
  "I have been with one company for over 30 years.",
  "I want to have kids, but never want to marry.",
  "I was in the Vietnam War.",
  "I attended multiple colleges.",
  "I'm an avid world traveler, most recently surfing in Nicaragua.",
  "This is my first Ted event!",
  "I love to ski all over the country.",
  "I love to work out.",
  "I run a non-profit for high school students continuing their theatrical education.",
  "My goal is to travel outside of the country each year and explore a new place!",
  "I've performed the spaghetti challenge as a learning exercise numerous times in our offices.",
  "I used to play video games competitively!",
  "I went to military school.",
  "I speak fluent German!",
  "I love Disney movies.",
  "This is my first TEDx event!",
  "I am the second child.",
  "I like to box.",
  "I coined 'Go big or go home'.",
  "I have had 12 tattoos, and 19 piercings (1 in my nose, 18 in my ears) and have about 10 more piercings to go before I finish my ear.",
  "I am a big TEDx fan.",
  "This is my first time attending Tedtalk.",
  "I like to draw linework cartoonish drawings of chairs.",
  "I am a private artist and paint often.",
  "I was once featured as a screensaver for my former employer",
  "I got lost for a day hiking in Peru with 2 friends.",
  "I won a hamburger eating contest.",
  "I have just become a mentor to a highschool student.",
  "I was a substitute Sunday School Teacher for 2 months.",
  "I love learning new topics and ideas.",
  "I like to surf.",
  "I make my own hot sauce.",
  "I am a chef.",
  "I love good puns.",
  "I love to travel.",
  "I am a proud Boston Latin School graduate.",
  "I'm a graphic designer in UX designer's clothes.",
  "I went paragliding in Chamonix France.",
  "I love playing board games",
  "I was cosmopolitan's most eligible bachelor in 1996.",
  "I am from France.",
  "I remember when there were only 3 TV channels and they went off the air at midnight.",
  "I love brookline.",
  "I love to dance!",
  "I like to mow my lawn and shovel snow.",
  "I am known among friends and loved ones as 'The HoneyBun'.",
  "I once played violin in Central Park.",
  "I grew up in a carnival!",
  "I was born on New Year's Eve.",
  "I am now a docent at the Arnold Arboretum.",
  "I have 3 master's degrees and Parkinson's.",
  "I was bitten by a monkey.",
  "I'm scared of frogs.",
  "I am a former foster youth.",
  "I’ve played drums at the rock and roll hall of fame",
  "I spent many years performing magic and wanted to make that my career.",
  "My favorite animals are elephants, gorillas and beluga whales.",
  "I love running long distances through the mountains.",
  "I love Mezcal.",
  "I had 2 pet frogs growing up.",
  "I am an abalone diver.",
  "I am excited to visit!",
  "My roommate gave a TED Talk in Grand Forks!",
  "As an MIT intern, I designed a grocery shopping app, later used by Stop & Shop.",
  "I have the PTC gene.",
  "I love learning about space.",
  "My signature dish for holiday meals is rabbit in white wine.",
  "I am a scuba diver.",
  "I am a passionate racer and designed a race car from scratch when in college.",
  "I recently started an EdTech company in addition to my day job.",
  "My family is direct descendants of the first baby born on the Mayflower in Plymouth harbor.",
  "One-Time Nude model.",
  "I love diving with sharks.",
  "Chips and fries are my biggest diet staple.",
  "Enjoy baking bread in my wood oven.",
  "I read magazines starting from the back, and finish at the front.",
  "I love my cat",
  "I translated Enka to English.",
  "I am a student at UMass Boston!",
  "I'm soon to be a first time Grandmother and I am a long time social justice activist and advocate.",
  "I am an aspiring golfer.",
  "I visited Crimea right before it was  annexed.",
  "I've rowed on the River Thames.",
  "I was a collegiate athlete and received an engineering degree.",
  "I grew up in a family of 11 children.",
  "I'm currently researching distributed networks!",
  "I am terrified yet fascinated by space.",
  "I’ve never owned a TV.",
  "I can only fit four munchkins in my mouth.",
  "My grandfather swears my first words were 'Bob Barker.'",
  "I am beginning new chapter in my life.",
  "I can walk on my hands.",
  "I have never been to the JFK Library.",
  "I create maps.",
  "My family was Mennonite and lived in the same county in Pennsylvania for 8 generations.",
  "I once dated a circus clown.",
  "I love the JFK legacy.",
  "I can talk for 12 straight hours, about nothing.",
  "My 14 year old daughter and I are working on seeing all 50 states by her 18th birthday.",
  "it's my first visit of Tad talk.",
  "This will be my first TEDx Event.",
  "I've been fired 27 times.",
  "One day, my son tells me that he will research a special drug for me to extend my lifespan with the development of the technology.",
  "I’m an avid aspiring private pilot!",
  "I’m working to show people the ocean.",
  "I beat record breaking odds at birth and am doing amazing things!",
  "I grew up on a dirt road and had a pet potbelly pig when I was a teenager.",
  "I am Turkish-American.",
  "I study Quantum Physics.",
  "I am the son of a Top Open Scholar at Oxford.",
  "I attended Woodstock.",
  "I love boxing.",
  "I take the hubway into work every day.",
  "I suffered and overcame from severe bullying when I was a teenager and I think I will one day talk about it publicly.",
  "I adopted twins from Russia.",
  "I completed a 1000km bicycle trip in New Zealand.",
  "I am obsessed with D list celebrities.",
  "I am a  lover of tea.",
  "I never carry moderation to extremes when I am curious about something.",
  "Reading has always been a passion, I still have over 100 books from when I was a little girl.",
  "I play the piano.",
  "I can whistle and hum at the same time. I can also cross one eye only.",
  "I used to hack into the school printers to submit work past the deadline",
  "There was 8kb memory in my first computer.",
  "I can program in 5 languages.",
  "I apply technologies to my work everyday.",
  "I used to be a professional actor.",
  "I'm a docent at a Frank Lloyd Wright designed house in Manchester, NH and passionate about livable architecture.",
  "I sat in the seat in front of Rihanna when I saw Hamilton on Broadway.",
  "I live my life to eliminate things off my bucket list",
  "I've never watched Harry Potter saga.",
  "I am a former school board member.",
  "I travel whenever I can.",
  "I volunteer for the kids in disability sports program.",
  "I love to be inspired.",
  "I am always in the search of new things and cultures so that I can learn from it and create a change for my country",
  "I own a cat.",
  "I have a very severe case of wanderlust!",
  "I am interested in architectural design.",
  "I live with only one kidney!",
  "I want skydiving while I was deadly afraid of flying.",
  "I'm Brazilian and Israeli.",
  "Born and raised in Kingston, Jamaica.",
  "I’m a Former submariner in the United States Navy.",
  "I am humorous.",
  "I once was a competitive archer.",
  "I have never been to the JFK library.",
  "I went to a sheep cafe in Seoul!",
  "I am bringing the Singularity to Boston.",
  "I am a social impact entrepreneur working to improve access to eye care worldwide",
  "Sleeping is my hobby.",
  "I am a super geek for tech even though I work as a medical doctor.",
  "I have lived in Hawaii for the last 4 years after spending 51 years in NH & MA.",
  "I'd love to have an animal shelter!",
  "I love Spartan Races.",
  "I am a former educator turned professional.",
  "I design CT scanners.",
  "I met my fiancee at TEDxBeaconStreet.",
  "I like to think I can multi-task, but am too busy doing it to admit I can't.",
  "I think hunger should be eliminated in this country.",
  "I figure skate.",
  "The soundtrack to my wedding video is 'Don't Fence Me In'!",
  "I have learned some sign language from Perkins' inclusion speaker Jaimi Lard!",
  "I have always watched ted talks on youtube. It's is very interesting.",
  "I've watched a lot of TEDx Talks on youtube..",
  "I'm shy but no one believes me!",
  "I am the youngest of 8 children and married to the youngest of 8 children!",
  "I taught English in Japan for 3 years.",
  "According to my mom, I am addicted to Snapchat.",
  "I am training for a marathon.",
  "I am a scientist who appreciates the arts.",
  "I plan on running for Mayor in 2030.",
  "I'm a dancer, turned architect, turned city planner and now all about data and networks, a network scientist.",
  "Huge WBGH Fan.",
  "This will be my first TEDx talk.",
  "I am jewish.",
  "My name is very very long.",
  "The first time watching the TEDx Talk live.",
  "I would love to speak at the next event!",
  "I really like to work out.",
  "I love chasing my bucket list!",
  "I'm learning Chinese!",
  "I love performing at weddings. In fact I performed at the wedding of one of today's speakers!",
  "I've been a farmer and raised and milked a high quality holstein herd of cattle.",
  "I smile - maybe way too much.",
  "I have been to all of the US States and Canadian Provinces.",
  "I am a licensed auctioneer and minister",
  "Surfing makes me stoked!",
  "I am groot.",
  "I am a creative connector.",
  "My boyfriend says i'm a light in this world.",
  "I'm a Health and Wellness director by day and a superhero DJ by night.",
  "I love being a part of this group!",
  "I am interested in the Talks.",
  "I can wiggle my ears.",
  "I am a 2nd degree black belt in TaeKwonDo.",
  "I work on social venture investing.",
  "I have to verbally say Ctrl+Alt+Del in order for it to work. Like a spell",
  "I once tried out for a boy band!",
  "I get share my first TED experience with my best friend and the love of my life. Win-Win.",
  "I love the green dog program in Brookline, Ma.",
  "I went around US in a 32 days road trip.",
  "I play the keyboard and participate in open mics.",
  "I've recently added a hobby of going to the shooting range for fun.",
  "I have a parrot that barks.",
  "My nonprofit in launching a new community based natural science educational program and coral farm in Holyoke, MA.",
  "I love chocolate cakes but hate chocolate bars.",
  "One day I hope to be a TED presenter. Titled 'Sister Citizen'.",
  "World championship dodgeballer.",
  "I have never had a girlfriend..",
  "I often have lucid dreams, I also often have nested dreams (i.e. dreams inside dreams, some of which are lucid).",
  "I love TED talks.",
  "I'm a painter.",
  "I'm interested in this event.",
  "I can learn more new idea, getting more new and fresh information.",
  "I give strangers love notes!",
  "I want to become a speaker!",
  "Know Tai Chi yang style short form.",
  "I have ridden on top of a train in Nariz Del Diablo in Ecuador!",
  "I have been to 14 countries.",
  "I'm a Commercially rated pilot.",
  "I like volunteering at soccer matches.",
  "I’m passionate about helping others get more comfortable with new technologies.",
  "I can move my ears and love rock climbing.",
  "I am excited to learn!",
  "I'm a twin.",
  "I am friendly.",
  "I can touch the tip of my nose with my tongue.",
  "I marched in Dwight D. Eisenhower's Inaugural Parade wearing a coonskin cap.",
  "I am a maker.",
  "I look forward to freedom and time to learn after retirement.",
  "I drove my first car into a lake.",
  "I enjoy paddling.",
  "I love food.",
  "I walked 500 miles across Spain.",
  "I'm a fiber artist.",
  "I like things to be even numbers.  For instance, I prefer words that have an even number of letters.",
  "I love sleeping out in the Yukon.",
  "I am the president of local environmental non profit.",
  "I can do the worm backwards.",
  "Advanced mixed gas rescue scuba diver with over 600 recorded dives.",
  "I'm fluent in three languages.",
  "I avoid using numbers that are multiples of 5.",
  "I like to bake bread.",
  "I want to know everything about everything."
]
